/*
    NUMBER GUESSING PROGRAM
    range (1 to 100)

    1st loop
    e.g : guess -> 12 (by user)
          random -> 43 (by system)
    this continues until the guess is equal to the random number
    the random is generated by the computer and its fixed .
            
*/

#include <stdio.h>

#include <stdlib.h>// to generate the random number we need to include to header files

#include <time.h>// for seeding the random value

int main(){

    int random,guess;
    int no_of_guess = 0;
    // seeding function
    srand(time(NULL));// on the basis of current time it will seed random value

    printf("===WELCOME TO THE GAME=== \n\n");
    random = rand() % 100 + 1;
    do{

        printf("PLEASE ENTER YOUR GUESS : (1 to 100)   \n\n");
         // generating the random number
        // generating between 0 to 100

        scanf("%d",&guess);

        /* as soon as the loop is recalled 
        i.e, the user got the wrong guess the 
        no_of_guess variable will be incresed */

        no_of_guess++;
        
        if(guess < random)
        {
            // 12 < 43 
            printf("GUESS LARGER NUMBER \n\n");
        }
        else if(guess > random )
        {
            //43 > 12
            printf("GUESS SMALLER NUMBER \n\n");
        }
        else 
        {
            // guess = random
            printf("===CONGRATULATION===\n\n");
            printf("\nYou have guessed the number in %d attempts \n",no_of_guess);
        }

    }while(guess!=random);

}